name: Testes Regressivos

on:
  pull_request:
    branches: [ main ]

jobs:
  RunTest:
    container:
      image: docker.io/roob3x/teste

    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: mvn test -Dtest=TestRunner cluecumber-report:reporting