name: Testes Regressivos

on:
  pull_request:
    branches: [ main ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        uses: docker://docker.io/roob3x/teste
        run: mvn test -Dtest=TestRunner cluecumber-report:reporting